[package]
description = "LSP for LLMs"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "llm-lsp"
version = "0.0.0"

[dependencies]
crossbeam-channel = "0.5.12"
lsp-server = "0.7.6"
lsp-types = "0.95.1"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
